[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# 1. Định cấu hình Proxy cho API Routes đến backend Vercel
[[redirects]]
  from = "/api/*"
  to = "https://ript-1307-nhom-6-kthp.vercel.app/api/:splat"
  status = 200
  force = true

# 2. Định cấu hình SPA Router Redirects để tránh lỗi 404 khi F5 tải lại trang
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200